//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ent_Enterprise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ent_Enterprise()
        {
            this.Ent_Address = new HashSet<Ent_Address>();
            this.Ent_Document = new HashSet<Ent_Document>();
            this.Ent_Telephone = new HashSet<Ent_Telephone>();
            this.Sys_User2 = new HashSet<Sys_User>();
        }
    
        public int idEnterprise { get; set; }
        public string idEnterpriseSource { get; set; }
        public string nmEnterprise { get; set; }
        public string nmNick { get; set; }
        public Nullable<System.DateTime> dtBirth { get; set; }
        public string dsEmail { get; set; }
        public string dsOccupation { get; set; }
        public string flStatus { get; set; }
        public int idUserCreate { get; set; }
        public System.DateTime dtCreate { get; set; }
        public int idUserLastUpdate { get; set; }
        public System.DateTime dtLastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Address> Ent_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Document> Ent_Document { get; set; }
        public virtual Sys_User Sys_User { get; set; }
        public virtual Sys_User Sys_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Telephone> Ent_Telephone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_User> Sys_User2 { get; set; }
    }
}
