//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ent_Document
    {
        public int idDocument { get; set; }
        public int idEnterprise { get; set; }
        public string cdDocument { get; set; }
        public string cdDocumentHash { get; set; }
        public string tpDocument { get; set; }
        public Nullable<int> idFile { get; set; }
        public int idUserCreate { get; set; }
        public System.DateTime dtCreate { get; set; }
        public int idUserLastUpdate { get; set; }
        public System.DateTime dtLastUpdate { get; set; }
    
        public virtual Ent_Enterprise Ent_Enterprise { get; set; }
        public virtual Sys_File Sys_File { get; set; }
        public virtual Ent_DocumentType Ent_DocumentType { get; set; }
        public virtual Sys_User Sys_User { get; set; }
        public virtual Sys_User Sys_User1 { get; set; }
    }
}
