//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_TransactionSignature
    {
        public long idSignature { get; set; }
        public System.Guid idTransaction { get; set; }
        public string imSignature { get; set; }
        public Nullable<System.DateTime> dtCreate { get; set; }
    
        public virtual Pay_Transaction Pay_Transaction { get; set; }
    }
}
