//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_Transaction()
        {
            this.Pay_TransactionSignature = new HashSet<Pay_TransactionSignature>();
            this.Pay_Transaction1 = new HashSet<Pay_Transaction>();
            this.Pay_CashReceipt = new HashSet<Pay_CashReceipt>();
            this.Sys_MerchantReceipt = new HashSet<Sys_MerchantReceipt>();
        }
    
        public System.Guid idTransaction { get; set; }
        public long idMobile { get; set; }
        public int idMerchant { get; set; }
        public Nullable<System.DateTime> dtCreate { get; set; }
        public Nullable<System.DateTime> dtLastUpdate { get; set; }
        public string flStatus { get; set; }
        public string acquirer { get; set; }
        public string acquirerNSU { get; set; }
        public string acquirerResponseCode { get; set; }
        public string authorizationNumber { get; set; }
        public string cardBIN { get; set; }
        public string cardBrand { get; set; }
        public string cardBrandCode { get; set; }
        public string clisitefConfirmationData { get; set; }
        public string clisitefRequestNumber { get; set; }
        public string customerEmail { get; set; }
        public string customerPhone { get; set; }
        public string customerReceipt { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string fiscalDate { get; set; }
        public string fiscalHour { get; set; }
        public string installmentAmount { get; set; }
        public Nullable<int> isTest { get; set; }
        public string issuerInstallmentAllowed { get; set; }
        public string maxIssuerInstallments { get; set; }
        public string maxMerchantInstallments { get; set; }
        public string merchantEmail { get; set; }
        public string merchantInstallmentAllowed { get; set; }
        public string merchantName { get; set; }
        public string merchantReceipt { get; set; }
        public Nullable<int> operation { get; set; }
        public string paymentFunction { get; set; }
        public string paymentFunctionDescription { get; set; }
        public string paymentType { get; set; }
        public string pinpadInfo { get; set; }
        public string pinpadSerialNumber { get; set; }
        public string refundDate { get; set; }
        public string refundDocumentNumber { get; set; }
        public string sitefNSU { get; set; }
        public string sitefVersion { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> statusCode { get; set; }
        public string timestamp { get; set; }
        public string token { get; set; }
        public Nullable<int> type { get; set; }
        public string value { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<long> idSignature { get; set; }
        public string cardType { get; set; }
        public Nullable<System.Guid> idTransactionParent { get; set; }
    
        public virtual Sys_Merchant Sys_Merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_TransactionSignature> Pay_TransactionSignature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_Transaction> Pay_Transaction1 { get; set; }
        public virtual Pay_Transaction Pay_Transaction2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_CashReceipt> Pay_CashReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_MerchantReceipt> Sys_MerchantReceipt { get; set; }
    }
}
