//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_CashReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_CashReceipt()
        {
            this.Sys_MerchantReceipt = new HashSet<Sys_MerchantReceipt>();
        }
    
        public long idCashReceipt { get; set; }
        public System.Guid idTransaction { get; set; }
        public int installmentNumber { get; set; }
        public int installmentAmount { get; set; }
        public string installmentValue { get; set; }
        public string value { get; set; }
        public int idRate { get; set; }
        public string rateCash { get; set; }
        public string rateCredit { get; set; }
        public string rateInstallment { get; set; }
        public string rateAnticipated { get; set; }
        public string bankOrigin { get; set; }
        public string agencyOrigin { get; set; }
        public string accountOrigin { get; set; }
        public string accountTypeOrigin { get; set; }
        public string operationOrigin { get; set; }
        public string bankDestination { get; set; }
        public string agencyDestination { get; set; }
        public string accountDestination { get; set; }
        public string accountTypeDestination { get; set; }
        public string operationDestination { get; set; }
        public System.DateTime dtPaymentMade { get; set; }
        public System.DateTime dtPayment { get; set; }
        public string flAnticipated { get; set; }
        public string flStatus { get; set; }
        public int idUserCreate { get; set; }
        public Nullable<int> idUserLastUpdate { get; set; }
        public System.DateTime dtCreate { get; set; }
        public Nullable<System.DateTime> dtLastUpdate { get; set; }
    
        public virtual Pay_Rate Pay_Rate { get; set; }
        public virtual Pay_Transaction Pay_Transaction { get; set; }
        public virtual Sys_User Sys_User { get; set; }
        public virtual Sys_User Sys_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_MerchantReceipt> Sys_MerchantReceipt { get; set; }
    }
}
