//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pay_Rate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pay_Rate()
        {
            this.Pay_CashReceipt = new HashSet<Pay_CashReceipt>();
            this.Sys_MerchantReceipt = new HashSet<Sys_MerchantReceipt>();
            this.Pay_RateItems = new HashSet<Pay_RateItems>();
        }
    
        public int idRate { get; set; }
        public string cdRate { get; set; }
        public string nmRate { get; set; }
        public string flMerchant { get; set; }
        public string flAnticipated { get; set; }
        public string flStatus { get; set; }
        public int idUserCreate { get; set; }
        public Nullable<int> idUserLastUpdate { get; set; }
        public System.DateTime dtCreate { get; set; }
        public Nullable<System.DateTime> dtLastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_CashReceipt> Pay_CashReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_MerchantReceipt> Sys_MerchantReceipt { get; set; }
        public virtual Sys_User Sys_User { get; set; }
        public virtual Sys_User Sys_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_RateItems> Pay_RateItems { get; set; }
    }
}
