//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_User()
        {
            this.Ent_Address = new HashSet<Ent_Address>();
            this.Ent_Address1 = new HashSet<Ent_Address>();
            this.Ent_Document = new HashSet<Ent_Document>();
            this.Ent_Document1 = new HashSet<Ent_Document>();
            this.Ent_DocumentType = new HashSet<Ent_DocumentType>();
            this.Ent_DocumentType1 = new HashSet<Ent_DocumentType>();
            this.Ent_Enterprise = new HashSet<Ent_Enterprise>();
            this.Ent_Enterprise1 = new HashSet<Ent_Enterprise>();
            this.Ent_Telephone = new HashSet<Ent_Telephone>();
            this.Ent_Telephone1 = new HashSet<Ent_Telephone>();
            this.Per_Address = new HashSet<Per_Address>();
            this.Per_Address1 = new HashSet<Per_Address>();
            this.Per_Document = new HashSet<Per_Document>();
            this.Per_Document1 = new HashSet<Per_Document>();
            this.Per_DocumentType = new HashSet<Per_DocumentType>();
            this.Per_DocumentType1 = new HashSet<Per_DocumentType>();
            this.Per_Person = new HashSet<Per_Person>();
            this.Per_Person1 = new HashSet<Per_Person>();
            this.Per_Telephone = new HashSet<Per_Telephone>();
            this.Per_Telephone1 = new HashSet<Per_Telephone>();
            this.Pos_PinPad = new HashSet<Pos_PinPad>();
            this.Pos_PinPad1 = new HashSet<Pos_PinPad>();
            this.Sys_Access = new HashSet<Sys_Access>();
            this.Sys_Access1 = new HashSet<Sys_Access>();
            this.Sys_File = new HashSet<Sys_File>();
            this.Sys_File1 = new HashSet<Sys_File>();
            this.Sys_ForgotPassword = new HashSet<Sys_ForgotPassword>();
            this.Sys_Merchant = new HashSet<Sys_Merchant>();
            this.Sys_Merchant1 = new HashSet<Sys_Merchant>();
            this.Sys_MerchantPinPad = new HashSet<Sys_MerchantPinPad>();
            this.Sys_Module = new HashSet<Sys_Module>();
            this.Sys_Module1 = new HashSet<Sys_Module>();
            this.Sys_Role = new HashSet<Sys_Role>();
            this.Sys_Role1 = new HashSet<Sys_Role>();
            this.Sys_SmsLog = new HashSet<Sys_SmsLog>();
            this.Sys_System = new HashSet<Sys_System>();
            this.Sys_System1 = new HashSet<Sys_System>();
            this.Sys_SystemType = new HashSet<Sys_SystemType>();
            this.Sys_SystemType1 = new HashSet<Sys_SystemType>();
            this.Sys_User1 = new HashSet<Sys_User>();
            this.Sys_User11 = new HashSet<Sys_User>();
            this.Sys_UserLoginHistory = new HashSet<Sys_UserLoginHistory>();
            this.Sys_UserPasswordHistory = new HashSet<Sys_UserPasswordHistory>();
            this.Sys_UserPasswordHistory1 = new HashSet<Sys_UserPasswordHistory>();
            this.Sys_UserPasswordHistory2 = new HashSet<Sys_UserPasswordHistory>();
            this.Sys_UserSystem = new HashSet<Sys_UserSystem>();
            this.Sys_UserSystem1 = new HashSet<Sys_UserSystem>();
            this.Sys_WebmailLog = new HashSet<Sys_WebmailLog>();
            this.Sys_UserSession = new HashSet<Sys_UserSession>();
            this.Sys_UserSession1 = new HashSet<Sys_UserSession>();
            this.Pay_CashReceipt = new HashSet<Pay_CashReceipt>();
            this.Pay_CashReceipt1 = new HashSet<Pay_CashReceipt>();
            this.Pay_Rate = new HashSet<Pay_Rate>();
            this.Pay_Rate1 = new HashSet<Pay_Rate>();
            this.Pay_RateItems = new HashSet<Pay_RateItems>();
            this.Pay_RateItems1 = new HashSet<Pay_RateItems>();
            this.Sys_MerchantReceipt = new HashSet<Sys_MerchantReceipt>();
            this.Sys_MerchantReceipt1 = new HashSet<Sys_MerchantReceipt>();
        }
    
        public int idUser { get; set; }
        public Nullable<int> idRole { get; set; }
        public Nullable<int> idPerson { get; set; }
        public Nullable<int> idEnterprise { get; set; }
        public string nmUser { get; set; }
        public string dsEmail { get; set; }
        public string dsPassword { get; set; }
        public string dsAcessToken { get; set; }
        public string dsSession { get; set; }
        public Nullable<System.DateTime> dtExpire { get; set; }
        public string stUser { get; set; }
        public Nullable<int> idUserCreate { get; set; }
        public System.DateTime dtCreate { get; set; }
        public Nullable<int> idUserLastUpdate { get; set; }
        public System.DateTime dtLastUpdate { get; set; }
        public Nullable<System.DateTime> dtLastSession { get; set; }
        public Nullable<int> idMerchant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Address> Ent_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Address> Ent_Address1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Document> Ent_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Document> Ent_Document1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_DocumentType> Ent_DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_DocumentType> Ent_DocumentType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Enterprise> Ent_Enterprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Enterprise> Ent_Enterprise1 { get; set; }
        public virtual Ent_Enterprise Ent_Enterprise2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Telephone> Ent_Telephone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ent_Telephone> Ent_Telephone1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Per_Address> Per_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Per_Address> Per_Address1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Per_Document> Per_Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Per_Document> Per_Document1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Per_DocumentType> Per_DocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Per_DocumentType> Per_DocumentType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Per_Person> Per_Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Per_Person> Per_Person1 { get; set; }
        public virtual Per_Person Per_Person2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Per_Telephone> Per_Telephone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Per_Telephone> Per_Telephone1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pos_PinPad> Pos_PinPad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pos_PinPad> Pos_PinPad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Access> Sys_Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Access> Sys_Access1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_File> Sys_File { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_File> Sys_File1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_ForgotPassword> Sys_ForgotPassword { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Merchant> Sys_Merchant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Merchant> Sys_Merchant1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_MerchantPinPad> Sys_MerchantPinPad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Module> Sys_Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Module> Sys_Module1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Role> Sys_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Role> Sys_Role1 { get; set; }
        public virtual Sys_Role Sys_Role2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_SmsLog> Sys_SmsLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_System> Sys_System { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_System> Sys_System1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_SystemType> Sys_SystemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_SystemType> Sys_SystemType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_User> Sys_User1 { get; set; }
        public virtual Sys_User Sys_User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_User> Sys_User11 { get; set; }
        public virtual Sys_User Sys_User3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_UserLoginHistory> Sys_UserLoginHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_UserPasswordHistory> Sys_UserPasswordHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_UserPasswordHistory> Sys_UserPasswordHistory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_UserPasswordHistory> Sys_UserPasswordHistory2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_UserSystem> Sys_UserSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_UserSystem> Sys_UserSystem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_WebmailLog> Sys_WebmailLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_UserSession> Sys_UserSession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_UserSession> Sys_UserSession1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_CashReceipt> Pay_CashReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_CashReceipt> Pay_CashReceipt1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_Rate> Pay_Rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_Rate> Pay_Rate1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_RateItems> Pay_RateItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_RateItems> Pay_RateItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_MerchantReceipt> Sys_MerchantReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_MerchantReceipt> Sys_MerchantReceipt1 { get; set; }
    }
}
