//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Merchant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Merchant()
        {
            this.Pay_Transaction = new HashSet<Pay_Transaction>();
            this.Sys_MerchantPinPad = new HashSet<Sys_MerchantPinPad>();
        }
    
        public int idMerchant { get; set; }
        public string dsEmail { get; set; }
        public string dsSoftDescriptor { get; set; }
        public string dsSitefNumber { get; set; }
        public string dsPinpadInfo { get; set; }
        public string flAdmin { get; set; }
        public string flDebug { get; set; }
        public string flStatus { get; set; }
        public Nullable<int> idUserCreate { get; set; }
        public System.DateTime dtCreate { get; set; }
        public Nullable<int> idUserLastUpdate { get; set; }
        public System.DateTime dtLastUpdate { get; set; }
        public string flAnticipated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pay_Transaction> Pay_Transaction { get; set; }
        public virtual Sys_User Sys_User { get; set; }
        public virtual Sys_User Sys_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_MerchantPinPad> Sys_MerchantPinPad { get; set; }
    }
}
