//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Access
    {
        public int idRole { get; set; }
        public int idModule { get; set; }
        public string tpAccess { get; set; }
        public int idUserCreate { get; set; }
        public Nullable<System.DateTime> dtCreate { get; set; }
        public Nullable<int> idUserLastUpdate { get; set; }
        public Nullable<System.DateTime> dtLastUpdate { get; set; }
    
        public virtual Sys_Module Sys_Module { get; set; }
        public virtual Sys_Role Sys_Role { get; set; }
        public virtual Sys_User Sys_User { get; set; }
        public virtual Sys_User Sys_User1 { get; set; }
    }
}
