//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_WebmailConf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_WebmailConf()
        {
            this.Sys_WebmailLog = new HashSet<Sys_WebmailLog>();
        }
    
        public int idWebmail { get; set; }
        public int idSequence { get; set; }
        public string dsFrom { get; set; }
        public string dsFromName { get; set; }
        public string dsHost { get; set; }
        public int nbPort { get; set; }
        public string cdUserName { get; set; }
        public string cdPassword { get; set; }
        public Nullable<bool> flEnableSsl { get; set; }
        public Nullable<bool> flUseDefaultCredentials { get; set; }
        public System.DateTime dtCreatedAt { get; set; }
        public Nullable<System.DateTime> dtUpdatedAt { get; set; }
        public bool flStatus { get; set; }
        public int nbAmountSend { get; set; }
        public int nbAmountLimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_WebmailLog> Sys_WebmailLog { get; set; }
    }
}
