//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_SmsLog
    {
        public int id { get; set; }
        public string nbSmsTo { get; set; }
        public string dsError { get; set; }
        public string dsMessage { get; set; }
        public string dsExtra { get; set; }
        public bool flStatus { get; set; }
        public bool flSent { get; set; }
        public Nullable<int> idSystem { get; set; }
        public Nullable<int> idUserCreate { get; set; }
        public System.DateTime dtCreatedAt { get; set; }
    
        public virtual Sys_System Sys_System { get; set; }
        public virtual Sys_User Sys_User { get; set; }
    }
}
