//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_MerchantPinPad
    {
        public int idMerchant { get; set; }
        public int idPinpad { get; set; }
        public string flStatus { get; set; }
        public System.DateTime dtCreate { get; set; }
        public int idUserLastUpdate { get; set; }
        public System.DateTime dtLastUpdate { get; set; }
    
        public virtual Pos_PinPad Pos_PinPad { get; set; }
        public virtual Sys_Merchant Sys_Merchant { get; set; }
        public virtual Sys_User Sys_User { get; set; }
    }
}
