//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ForgotPassword
    {
        public int idForgot { get; set; }
        public int idSecretAnswers { get; set; }
        public int idUser { get; set; }
        public string Answer { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string PasswordHint { get; set; }
    
        public virtual Sys_User Sys_User { get; set; }
    }
}
