//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_UserLoginHistory
    {
        public System.Guid idUserLoginHistory { get; set; }
        public int idUser { get; set; }
        public Nullable<int> idSystem { get; set; }
        public string dsAccessToken { get; set; }
        public string dsSession { get; set; }
        public string stUserLogin { get; set; }
        public string dsIpAddress { get; set; }
        public string dsAgent { get; set; }
        public System.DateTime dtCreate { get; set; }
    
        public virtual Sys_System Sys_System { get; set; }
        public virtual Sys_User Sys_User { get; set; }
    }
}
