//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPlay.Business.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Module()
        {
            this.Sys_Access = new HashSet<Sys_Access>();
        }
    
        public int idModule { get; set; }
        public string nmModule { get; set; }
        public string dsURLModule { get; set; }
        public int idRole { get; set; }
        public int idUserCreate { get; set; }
        public Nullable<System.DateTime> dtCreate { get; set; }
        public Nullable<int> idUserLastUpdate { get; set; }
        public Nullable<System.DateTime> dtLastUpdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Access> Sys_Access { get; set; }
        public virtual Sys_User Sys_User { get; set; }
        public virtual Sys_User Sys_User1 { get; set; }
    }
}
